# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fanga_development
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  username: postgres  
  password: mysecretpassword

test:
  <<: *default
  database: fanga_test
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  username: postgres  
  password: mysecretpassword