version: '2'
services:
  db:
    image: postgres:9.6.0
    ports:
      - 5432:5432  
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: '-Xms250m -Xmx250m'
  smtp:
    image: yrezgui/smtp-mail-server    
    ports:
      - 25:25
      - 3333:3333
  #kibana:
    #image: kibana
    #ports:
   #   - 5601:5601  
  web:
    build: ./fanga/
    command: bash -c "rm -rf /api_server/tmp/pids/* && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./fanga/:/api_server
    ports:
      - "3000:3000"
    depends_on:
      - db
      - smtp
    #  - kibana
      - elasticsearch

