version: '2'
services:
  db:
    image: postgres:9.6.0
  web:
    build: ./fanga/
    command: bash -c "rm -rf /api_server/tmp/pids/* && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./fanga/:/api_server
    ports:
      - "3000:3000"
    depends_on:
      - db